import type { Metadata } from "next";
import "./globals.css";
import AppNavigation from "./components/AppNavigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body suppressHydrationWarning>
    <AppNavigation />
        {children}
      </body>
    </html>
  );
}
